mysite/choose/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'choose/result', views.result, name='result'),
                       )

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('choose.urls', namespace='choose')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
                       )

mysite/choose/models.py
from django.db import models
import datetime
from django.utils import timezone

class Venue(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    distance = models.CharField(max_length=200)
    selected = models.BooleanField()

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

mysite/choose/forms.py
from django import forms
from models import Venue

class VenueForm(forms.ModelForm):
    selected = forms.BooleanField()

    class Meta:
        model = Venue

mysite/choose/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from models import Venue

import foursquare

#0dd682

API_URL = "https://api.foursquare.com/v2/venues/search"
FS_RADIUS = 20000
FS_COORDINATES = '42.6931325, 23.3244314'
CLIENT_ID = "35UKEYL1JB5SCBN1JHL4KTXSQWULWRELA5AMB1SN2UMDYSOK"
CLIENT_SECRET = "GOZQXTNPAXPC1GATPFIF02LBHROZZ3GGD2YRLMNHBG1VRCDI"

client = foursquare.Foursquare(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)

venues = client.venues.search(params={'ll': FS_COORDINATES, 'intent': 'browse', 'radius': FS_RADIUS})

venues_count = len(venues.values()[0])

selected_venue_id_list = []

# for v in Venue.objects.all():
#     v.delete()


def index(request):
    if len(Venue.objects.all()) != venues_count:
        for n in range(0, venues_count):
            venue = venues.values()[0][n]
            if "name" in venue:
                venue_name = venue["name"]
            else:
                venue_name = "n/a"
            if "address" in venue["location"]:
                venue_address = venue["location"]["address"]
            else:
                venue_address = "n/a"
            if venue['categories'][0]['primary'] and "name" in venue["categories"][0]:
                venue_category = venue["categories"][0]["name"]
            else:
                venue_category = "n/a"
            if "distance" in venue["location"]:
                venue_distance = str(venue["location"]["distance"])
            else:
                venue_distance = "n/a"

            v = Venue(name=venue_name,
                      address=venue_address,
                      category=venue_category,
                      distance=venue_distance,
                      selected=False
                      )
            if v not in Venue.objects.all():
                v.save()
    # venue = get_object_or_404(Venue, v_id)
    venue_list = Venue.objects.all()
    context = {'venue_list': venue_list, 'FS_COORDINATES': FS_COORDINATES, 'FS_RADIUS':FS_RADIUS / 1000}
    return render(request, 'choose/home.html', context)


        # try:
        #     selected_venue = venue.get(pk=request.POST[venue.name])
        # except (KeyError, Venue.DoesNotExist):
        #     return render(request, 'choose/home.html', {
        #         'venue': venue,
        #         'error_message': "You didn't select a venue.",
        #     })
        # else:
        #     selected_venue.selected = True
        #     selected_venue.save()
        #     return HttpResponseRedirect(reverse('choose:results'))

def result(request):
    selected_venue_list = []
    venue_list = Venue.objects.all()
    selected_venue_ids = request.POST.getlist('check_venue')
    for i in selected_venue_ids:
        for v in venue_list:
            if str(i).replace("/", "") == str(v.id):
                selected_venue_list.append(v)

    return render(request, "choose/result.html", {"selected_venue_list": selected_venue_list})

mysite/choose/templates/choose/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title> </title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'choose/css/bootstrap.min.css' %}" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			  <div class="col-sm-2">
				  <br><br>
				  <center>
					<img src="{% static 'choose/img/logo.png' %}" class="responsive-img" style='max-height:100px;' alt="face" width="100">
				  </center>
			  </div>
			  <div class="col-sm-10">
				  <br>
				  <center>
				  <h3> </h3>
				  </center>
			  </div>
		</div><hr>

		<div class="row">
		  <div class="col-sm-2">
		  <br>
		  <br>
		  </div> <!--col-sm-2-->
		  <div class="col-sm-10">

			<div class='container-fluid'>
			<br><br>
			   {% block content %}
			   {% endblock %}
			</div>
		  </div>
		</div>
	</div>
	<footer>
	</br></br>
	</footer>

</body>

</html>

mysite/choose/templates/choose/home.html
{% extends "choose/header.html" %}
{% block content %}
<h3  align="center"><font color="white">Showing venues in radius of {{ FS_RADIUS }}km with coordinates: {{ FS_COORDINATES }}</font></h3>
<h4  align="center"><font color="white">Please select as many as necessary:</font></h4>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'choose:result' %}" method="post">
    {% csrf_token %}

        <style>
        table, th, td {
            border: 1px solid white;
            border-collapse: collapse;
        }
        th, td {

            max-width:90%;
            white-space:nowrap;
            padding: 3px;
        }
        th {
            text-align: center;
            color: white;
        }
        </style>


        <table align="center">
            <tr>
                <th></th>
                <th>Name</th>
                <th>Address</th>
                <th>Category</th>
                <th>Distance</th>
            </tr>
            {% for venue in venue_list %}
            <tr>

    <td width="60" align="center"><input type="checkbox" name="check_venue" id="venue{{ forloop.counter }}" value={{venue.id}}/></td>
    <td align="left"><label for="venue{{ forloop.counter }}"><b>{{ venue.name }}</b></label><br /></td>
    <td align="left"><label for="venue{{ forloop.counter }}"><b>{{ venue.address }}</b></label><br /></td>
    <td align="left"><label for="venue{{ forloop.counter }}"><b>{{ venue.category }}</b></label><br /></td>
    <td align="center" width="100"><label for="venue{{ forloop.counter }}"><b>{{ venue.distance }}m</b></label><br /></td>

            </tr>
            {% endfor %}
        </table>
        <br>
        <input type="submit" style="margin-left: 50%;" name="submit" value="Submit" />
    </form>
{% endblock %}

mysite/choose/templates/choose/result.html
{% extends "choose/header.html" %}
{% block content %}
<h3><font color="white" style="margin-left: 42%">Selected venues:</font></h3>

    {% for v in selected_venue_list %}
        <center><b>{{ v }}</b>
        <br>
    {% endfor %}
        <br>
        <a href="{% url 'choose:index' %}"><font color="white" size="4">Select again?</font></a>
        </center>
{% endblock %}

/home/dzhrt/PycharmProjects/untitled/pyth/you_local_2